DELETE FROM [dbo].[EmailTemplate]
GO
SET IDENTITY_INSERT [dbo].[EmailTemplate] ON 

INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (1, N'Cipl', N'Submit', N'Requestor', N'CIPL @RequestNo SUBMITTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export CIPL Form has been submitted to @ApproverPosition for review & approval in 24 hours after received this request.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
 	<tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To check the progress, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (2, N'Cipl', N'Approval', N'Approver', N'CIPL @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>You have one Export CIPL form Approval Request for your review & approval in 24 hours after received this request.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>Kindly  please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (3, N'Cipl', N'Revise', N'Requestor', N'CIPL @RequestNo REVISED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export CIPL Form has been requested for revision by your approver.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>Kindly  please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (4, N'Cipl', N'Revise', N'Approver', N'CIPL @RequestNo REVISED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>You have requested a revision on Export CIPL form with details.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	 <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
	  <tr>
			<td>Notes</td>
			<td>: @Note</td>
		</tr>
   </table>
   <br />  <span>To check the progress, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (5, N'Cipl', N'Reject', N'Requestor', N'CIPL @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export CIPL Form has been rejected by your approver.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
	<tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (6, N'Cipl', N'Reject', N'Approver', N'CIPL @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>An Export CIPL form has been rejected with details.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	<tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (7, N'Cipl', N'Approved', N'Requestor', N'CIPL @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export CIPL Form has been fully approved.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (8, N'Cipl', N'Approved', N'Approver', N'CIPL @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>An Export CIPL form has been fully approved with details.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export CIPL Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export CIPL Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, kindly  please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (9, N'GoodReceive', N'Submit', N'Requestor', N'GR @RequestNo SUBMITTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Export GR Form has been submitted to the Export CIPL Requestor for review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>ExportGR Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Export GR Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To check the progress, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10, N'GoodReceive', N'Approval', N'Approver', N'GR @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>You have one Export GR form Approval Request for your review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Export GR Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Export GR Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Requestor Name</td>
		<td>: @RequestorName</td>
	</tr>
	<tr>
		<td>Requestor ID</td>
		<td>: @RequestorEmpID</td>
	</tr>
</table><br />
<span>Kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (11, N'GoodReceive', N'Revise', N'Requestor', N'GR @RequestNo REVISED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Export GR Form has been requested for revision by your approver.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Export GR Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Export GR Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>Kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (12, N'GoodReceive', N'Revise', N'Approver', N'GR @RequestNo REVISED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>You have requested a revision on Export GR form with details.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export GR Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export GR Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To check the progress, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (13, N'GoodReceive', N'Reject', N'Requestor', N'GR @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export GR Form has been rejected by your approver.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export GR Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export GR Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (14, N'GoodReceive', N'Reject', N'Approver', N'GR @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>An Export GR form has been rejected with details.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export GR Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export GR Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, kindly  please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (15, N'GoodReceive', N'Approved', N'Requestor', N'GR @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @RequestorName,</span><br /><br />  <span>Your Export GR Form has been fully approved.</span><br /><br />  
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export GR Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export GR Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Superior Name</td>
         <td>: @SuperiorName</td>
      </tr>
      <tr>
         <td>Superior ID</td>
         <td>: @SuperiorEmpID</td>
      </tr>
	  <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
	<tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
	<tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
	<tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, please Log to:</span> <br /><br />  
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action   
      <li>By desktop click <a href="@DesktopLink">here</a> for further action  
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>  
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (16, N'GoodReceive', N'Approved', N'Approver', N'GR @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
   <span>Dear @ApproverName,</span><br /><br />  <span>An Export GR form has been fully approved with details.</span><br /><br />       
   <table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
      <tr>
         <td>Export GR Number&nbsp;&nbsp;</td>
         <td>: @RequestNo</td>
      </tr>
      <tr>
         <td>Export GR Date</td>
         <td>: @CreatedDate</td>
      </tr>
      <tr>
         <td>Requestor Name</td>
         <td>: @RequestorName</td>
      </tr>
      <tr>
         <td>Requestor ID</td>
         <td>: @RequestorEmpID</td>
      </tr>
      <tr>
         <td>No Do</td>
         <td>: @DO</td>
      </tr>
      <tr>
         <td>No DA</td>
         <td>: @DA</td>
      </tr>
      <tr>
         <td>No Reference</td>
         <td>: @NoReference</td>
      </tr>
      <tr>
         <td>Branch</td>
         <td>: @CIPLBranchName</td>
      </tr>
   </table>
   <br />  <span>To view the detail, kindly  please Log to:</span> <br /><br />       
   <ol type="a">
      <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action           
      <li>By desktop click <a href="@DesktopLink">here</a> for further action       
   </ol>
   <br />  <span>Best regards,</span><br /><span>EMCS Application</span>  <br /><br />  <span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>    
</body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (17, N'Cargo', N'Submit', N'Requestor', N'CL @RequestNo SUBMITTED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @RequestorName,</span><br><br><span>Your Export CL Form has been submitted to @ApproverPosition for review & approval in 24 hours after received this request.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Superior Name</td><td>: @SuperiorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>To check the progress, please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (18, N'Cargo', N'Approval', N'Approver', N'CL @RequestNo WAITING APPROVAL', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @ApproverName,</span><br><br><span>You have one Export CL form Approval Request for your review & approval in 24 hours after received this request.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Requestor Name</td><td>: @RequestorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>Kindly please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (19, N'Cargo', N'Revise', N'Requestor', N'CL @RequestNo REVISED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @RequestorName,</span><br><br><span>Your Export CL Form has been requested for revision by your approver.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Superior Name</td><td>: @SuperiorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>Kindly please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (20, N'Cargo', N'Revise', N'Approver', N'CL @RequestNo REVISED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @ApproverName,</span><br><br><span>You have requested a revision on Export CL form with details.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Requestor Name</td><td>: @RequestorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>To check the progress, please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (21, N'Cargo', N'Reject', N'Requestor', N'CL @RequestNo REJECTED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @RequestorName,</span><br><br><span>Your Export CL Form has been rejected by your approver.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Superior Name</td><td>: @SuperiorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>To view the detail, please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (22, N'Cargo', N'Reject', N'Approver', N'CL @RequestNo REJECTED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @ApproverName,</span><br><br><span>An Export CL form has been rejected with details.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Requestor Name</td><td>: @RequestorName</td></tr></table><br><span>To view the detail, kindly please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (23, N'Cargo', N'Approved', N'Requestor', N'CL @RequestNo APPROVED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @RequestorName,</span><br><br><span>Your Export CL Form has been fully approved.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Superior Name</td><td>: @SuperiorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>To view the detail, please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (24, N'Cargo', N'Approved', N'Approver', N'CL @RequestNo APPROVED', N'<body style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><span>Dear @ApproverName,</span><br><br><span>An Export CL form has been fully approved with details.</span><br><br><table border="0" style="font-family:verdana,helvetica,sans-serif;font-size:10pt"><tr><td>Export CL Number&nbsp;&nbsp;</td><td>: @RequestNo</td></tr><tr><td>Export CL Date</td><td>: @CreatedDate</td></tr><tr><td>Requestor Name</td><td>: @RequestorName</td></tr><tr><td>No Do</td><td>: @DO</td></tr><tr><td>No DA</td><td>: @DA</td></tr><tr><td>No Reference</td><td>: @NoReference</td></tr><tr><td>Branch</td><td>: @CIPLBranchName</td></tr></table><br><span>To view the detail, kindly please Log to:</span><br><br><ol type="a"><li>By mobile/Smart phone (Internet connection) click<a href="@MobileLink">here</a>for further action<li>By desktop click<a href="@DesktopLink">here</a>for further action</ol><br><span>Best regards,</span><br><span>EMCS Application</span><br><br><span style="font-size:9pt"><i>Do not reply this email, this email is automatically generated by system</i></span></body>', N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime), N'0', CAST(N'2019-02-10T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (25, N'Cipl', N'InfoCKB', N'CKB', N'CIPL @RequestNo Complete', N'<!DOCTYPE html>
<html>

<head>
    <title></title>
</head>

<body style="font-family: verdana, helvetica, sans-serif; font-size: 10pt;">
    <p><span>Dear CKB,</span></p>
    <p><br></p>
    <p><span>You have <span style="color: rgb(0, 0, 0); font-family: verdana, helvetica, sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">one of&nbsp;</span>Export Delivery Instruction (EDI) request with details. </span></p>
    
    
    <p><br></p>
    <table border="0" style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
        <tbody>
            <tr>
                <td>Export <span style="color: rgb(0, 0, 0); font-family: verdana, helvetica, sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">EDI&nbsp;</span>Number &nbsp;</td>
                <td>: @RequestNo</td>
            </tr>
            <tr>
                <td>Export <span style="color: rgb(0, 0, 0); font-family: verdana, helvetica, sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">EDI&nbsp;</span>Date</td>
                <td>: @CreatedDate</td>
            </tr>
            <tr>
                <td>Requestor Name</td>
                <td>: @RequestorName</td>
            </tr>
            <tr>
                <td>Requestor ID</td>
                <td>: @RequestorEmpID</td>
            </tr>
		<tr>
                <td>CIPL Number &nbsp;</td>
                <td>: @CIPLNo</td>
            </tr>
		<tr>
                <td>Branch Number &nbsp;</td>
                <td>: @CIPLBranchName</td>
            </tr>
		<tr>
                <td>PIC Pickup Points &nbsp;</td>
                <td>: @PICPickupPoints</td>
            </tr>
		<tr>
                <td>Pickup Points Area &nbsp;</td>
                <td>: @PickupPointsArea</td>
            </tr>
        </tbody>
    </table>
    <p><br></p>
	<p><span><b>"Please follow up to create RG before pickup goods"</b></span></p>
    <p><span>To view the detail, kindly please Log to:</span></p>
    <p><br></p>
    <ol type="a">
        <li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action</li>
        <li>By desktop click <a href="@DesktopLink">here</a> for further action</li>
    </ol>
    <p><br></p>
    <p><span>Best regards,</span></p>
    <p><span>EMCS Application</span></p>
    <p><br></p>
    <p><span style="font-size: 9pt;"><em>Do not reply this email, this email is automatically generated by system</em></span></p>
</body>

</html>', N'IT', CAST(N'2020-07-03T00:00:00' AS SmallDateTime), N'IT', CAST(N'2020-07-03T00:00:00' AS SmallDateTime))
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (26, N'RFC', N'Approval', N'Requestor', N'RFC @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) form has been submitted to IMEX Superior for review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />

<span>To check the progress, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (27, N'RFC', N'Approval', N'Approver', N'RFC @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>You have one Request for Changes Approval for your review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request No&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Export CIPL Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Requestor Name</td>
		<td>: @RequestorName</td>
	</tr>
	<tr>
		<td>Requestor ID</td>
		<td>: @RequestorEmpID</td>
	</tr>
</table><br />
<span>Kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (28, N'RFC', N'Approved', N'Requestor', N'RFC @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) has been fully approved.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (29, N'RFC', N'Approved', N'Approver', N'RFC @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>Thank you for your approval this Request for Changes (RFC) below.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>

	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Requestor Name</td>
		<td>: @RequestorName</td>
	</tr>
	<tr>
		<td>Requestor ID</td>
		<td>: @RequestorEmpID</td>
	</tr>
</table><br />
<span>To check the progress, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (30, N'RFC', N'Reject', N'Requestor', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) has been rejected by your approver.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (31, N'RFC', N'Reject', N'Approver', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>A Request for Changes (RFC) has been rejected with details.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10001, N'RFC', N'Reject', N'Approver', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>A Request for Changes (RFC) has been rejected with details.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10002, N'RFC', N'Approval', N'Requestor', N'RFC @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) form has been submitted to IMEX Superior for review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />

<span>To check the progress, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10003, N'RFC', N'Approval', N'Approver', N'RFC @RequestNo WAITING APPROVAL', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>You have one Request for Changes Approval for your review & approval in 24 hours after received this request.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request No&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Export CIPL Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Requestor Name</td>
		<td>: @RequestorName</td>
	</tr>
	<tr>
		<td>Requestor ID</td>
		<td>: @RequestorEmpID</td>
	</tr>
</table><br />
<span>Kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10004, N'RFC', N'Approved', N'Requestor', N'RFC @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) has been fully approved.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10005, N'RFC', N'Approved', N'Approver', N'RFC @RequestNo APPROVED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>Thank you for your approval this Request for Changes (RFC) below.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>

	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Request Reason</td>
		<td>: @RequestReason</td>
	</tr>
	<tr>
		<td>Requestor Name</td>
		<td>: @RequestorName</td>
	</tr>
	<tr>
		<td>Requestor ID</td>
		<td>: @RequestorEmpID</td>
	</tr>
</table><br />
<span>To check the progress, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10006, N'RFC', N'Reject', N'Requestor', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @RequestorName,</span><br /><br />
<span>Your Request for Changes (RFC) has been rejected by your approver.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10007, N'RFC', N'Reject', N'Approver', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>A Request for Changes (RFC) has been rejected with details.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
INSERT [dbo].[EmailTemplate] ([ID], [Module], [Status], [RecipientType], [Subject], [Message], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10008, N'RFC', N'Reject', N'Approver', N'RFC @RequestNo REJECTED', N'<body style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
<span>Dear @ApproverName,</span><br /><br />
<span>A Request for Changes (RFC) has been rejected with details.</span><br /><br />
<table border = ''0'' style="font-family: verdana, helvetica, sans-serif;font-size: 10pt;">
	<tr>
		<td>Request Number&nbsp;&nbsp;</td>
		<td>: @RequestNo</td>
	</tr>
	<tr>
		<td>Request Date</td>
		<td>: @CreatedDate</td>
	</tr>
	
	<tr>
		<td>Document Type</td>
		<td>: @DocumentType</td>
	</tr>
	
	<tr>
		<td>Document No</td>
		<td>: @DocumentNo</td>
	</tr>
	<tr>
		<td>Reject Reason</td>
		<td>: @ReasonIfRejected</td>
	</tr>
	<tr>
		<td>Superior Name</td>
		<td>: @SuperiorName</td>
	</tr>
	<tr>
		<td>Superior ID</td>
		<td>: @SuperiorEmpID</td>
	</tr>
</table><br />
<span>To view the detail, kindly  please Log to:</span> <br /><br />
<ol type="a">
	<li>By mobile/Smart phone (Internet connection) click <a href="@MobileLink">here</a> for further action
	<li>By desktop click <a href="@DesktopLink">here</a> for further action
</ol><br />
<span>Best regards,</span><br /><span>EMCS Application</span>
<br /><br />
<span style="font-size: 9pt;"><i>Do not reply this email, this email is automatically generated by system</i></span>
</body>', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[EmailTemplate] OFF
